baseURL = "https://www.djlechuck.fr"
title = "De tout et de rien"
# for smart copyright line, leave this blank and check [params.copyright]
copyright = ""

theme = "minimo"

disqusShortname = "djlechuck"
googleAnalytics = "UA-90814956-1"

Paginate = 5
preserveTaxonomyNames = true

enableRobotsTXT = true # generate robots.txt

# Syntax Highlighting ( https://gohugo.io/content-management/syntax-highlighting/ )
pygmentsCodefences = true

# Missing translations will default to this content language
defaultContentLanguage = "fr"

[params.info]
    description = "Ce qui me passe par la tête"
    title404 = "Ici c'est sûr, il n'y a rien !"

[params.assets]
    favicon = "favicon.ico"
    # customCSS = ["css/custom.css"]
    # customJS = ["js/custom.js"]
    gopher = "images/404-gopherize.png" # used in 404 template ( Generator: https://gopherize.me )

[params.copyright]
    prefix = ""
    holder = "DjLeChuck"
    startYear = "2018"
    suffix = ""

[params.settings]
    # date & time format: https://golang.org/pkg/time/
    dateFormat = "02 Jan 2006"
    listDateFormat = "02 Jan 2006"
    hideEntryNavigation = ["page"] # boolean / array of sections
    recentPostsLength = 4
    hideSocialMenu = false
    showReadingTime = false
    noTermCloudShuffle = false
    homepageSections = ["recent_posts", "tags"]

[params.opengraph.facebook]
    admins = [] # array of Facebook IDs
    appID = ""
    pageID = ""

[params.opengraph.twitter]
    page = "DjLeChuck" # Twitter page username

[params.seo]
    # Title Separator: - – — · • * ⋆ | ~ « » < >
    titleSeparator = "•"

[params.social]
    # codepen = "MunifTanjim"
    email = "djlechuck@gmail.com"
    # facebook = "MunifTanjim"
    github = "DjLeChuck"
    # instagram = "MunifTanjim"
    # linkedin = "muniftanjim"
    twitter = "DjLeChuck"
    # telegram = "MunifTanjim"
    # google_scholar = "qc6CJjYAAAAJ"

[params.social.config]
    platforms = [
        "github",
        #"facebook",
        "twitter",
        #"instagram",
        "email",
        #"codepen",
        #"linkedin",
        #"telegram",
        #"google_scholar"
    ]

[taxonomies]
    author = "authors"
    category = "categories"
    tag = "tags"

[permalinks]
    page = "/:slug/"
    post = "/:year/:month/:title/"

[[menu.main]]
    name = "Accueil"
    weight = -10
    identifier = "accueil"
    url = "/"

[[menu.about]]
    name = "À propos"
    weight = -20
    identifier = "a-propos"
    url = "/a-propos"

[blackfriday]
    hrefTargetBlank = true

[languages]
    # edit this block for your own language
    [languages.fr]
    lang = "fr"
    languageName = "Français"
    weight = 1
